### ISSUE TITLE
Doc creation errors

### ISSUE THREAD

**Issue by tieugene** [PydPiper/pylightxl#35]
push doc && make html:
```
reading sources... [100%] sourcecode/writexl                                                                                                                                      
.../pylightxl-1.53/doc/source/revlog.rst:84: WARNING: Unknown target name: "new".
.../pylightxl-1.53/doc/source/revlog.rst:84: WARNING: Unknown target name: "new".
WARNING: autodoc: failed to import function 'address2index' from module 'pylightxl.pylightxl'; the following exception was raised:
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/sphinx/util/inspect.py", line 325, in safe_getattr
    return getattr(obj, name, *defargs)
AttributeError: module 'pylightxl.pylightxl' has no attribute 'address2index'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/sphinx/ext/autodoc/importer.py", line 106, in import_object
    obj = attrgetter(obj, mangled_name)
  File "/usr/lib/python3.9/site-packages/sphinx/ext/autodoc/__init__.py", line 289, in get_attr
    return autodoc_attrgetter(self.env.app, obj, name, *defargs)
  File "/usr/lib/python3.9/site-packages/sphinx/ext/autodoc/__init__.py", line 2186, in autodoc_attrgetter
    return safe_getattr(obj, name, *defargs)
  File "/usr/lib/python3.9/site-packages/sphinx/util/inspect.py", line 341, in safe_getattr
    raise AttributeError(name) from exc
AttributeError: address2index

WARNING: autodoc: failed to import function 'index2address' from module 'pylightxl.pylightxl'; the following exception was raised:
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/sphinx/util/inspect.py", line 325, in safe_getattr
    return getattr(obj, name, *defargs)
AttributeError: module 'pylightxl.pylightxl' has no attribute 'index2address'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/sphinx/ext/autodoc/importer.py", line 106, in import_object
    obj = attrgetter(obj, mangled_name)
  File "/usr/lib/python3.9/site-packages/sphinx/ext/autodoc/__init__.py", line 289, in get_attr
    return autodoc_attrgetter(self.env.app, obj, name, *defargs)
  File "/usr/lib/python3.9/site-packages/sphinx/ext/autodoc/__init__.py", line 2186, in autodoc_attrgetter
    return safe_getattr(obj, name, *defargs)
  File "/usr/lib/python3.9/site-packages/sphinx/util/inspect.py", line 341, in safe_getattr
    raise AttributeError(name) from exc
AttributeError: index2address

WARNING: autodoc: failed to import function 'columnletter2num' from module 'pylightxl.pylightxl'; the following exception was raised:
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/sphinx/util/inspect.py", line 325, in safe_getattr
    return getattr(obj, name, *defargs)
AttributeError: module 'pylightxl.pylightxl' has no attribute 'columnletter2num'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/sphinx/ext/autodoc/importer.py", line 106, in import_object
    obj = attrgetter(obj, mangled_name)
  File "/usr/lib/python3.9/site-packages/sphinx/ext/autodoc/__init__.py", line 289, in get_attr
    return autodoc_attrgetter(self.env.app, obj, name, *defargs)
  File "/usr/lib/python3.9/site-packages/sphinx/ext/autodoc/__init__.py", line 2186, in autodoc_attrgetter
    return safe_getattr(obj, name, *defargs)
  File "/usr/lib/python3.9/site-packages/sphinx/util/inspect.py", line 341, in safe_getattr
    raise AttributeError(name) from exc
AttributeError: columnletter2num

WARNING: autodoc: failed to import function 'num2columnletters' from module 'pylightxl.pylightxl'; the following exception was raised:
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/sphinx/util/inspect.py", line 325, in safe_getattr
    return getattr(obj, name, *defargs)
AttributeError: module 'pylightxl.pylightxl' has no attribute 'num2columnletters'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/sphinx/ext/autodoc/importer.py", line 106, in import_object
    obj = attrgetter(obj, mangled_name)
  File "/usr/lib/python3.9/site-packages/sphinx/ext/autodoc/__init__.py", line 289, in get_attr
    return autodoc_attrgetter(self.env.app, obj, name, *defargs)
  File "/usr/lib/python3.9/site-packages/sphinx/ext/autodoc/__init__.py", line 2186, in autodoc_attrgetter
    return safe_getattr(obj, name, *defargs)
  File "/usr/lib/python3.9/site-packages/sphinx/util/inspect.py", line 341, in safe_getattr
    raise AttributeError(name) from exc
AttributeError: num2columnletters
```

**Comment by PydPiper** [comment]
Hi and thank you for considering using pylightxl! Thanks for submitting this documentation miss. We pushed the fix to the current master branch the doc's should be updated as well! See https://github.com/PydPiper/pylightxl/commit/5f21310d5bd805bda43ded58d10653200a09e1e2
