### ISSUE TITLE
Pylightxl Encoding Problem Proccessing Chinese excel File.

### ISSUE THREAD

**Issue by Leslielu** [PydPiper/pylightxl#51]
**Pylightxl Version**:1.56beta
**Python Version**:3.8.10

**Summary of Bug/Feature**:
When Pylightxl deal with a chinese excel file(xlsx), it encounter a encoding problem 

**Traceback**:
Traceback (most recent call last):
  File "tjexcel.py", line 103, in <module>
    main()
  File "tjexcel.py", line 98, in main
    xl.writexl(db=db, fn=myfilepath)
  File "C:\Program\py\pylightxl\pylightxl.py", line 559, in writexl
    writexl_alt_writer(db, fn)
  File "C:\Program\py\pylightxl\pylightxl.py", line 588, in writexl_alt_writer
    text = writexl_alt_app_text(db, temp_folder + '/docProps/app.xml')
  File "C:\Program\py\pylightxl\pylightxl.py", line 718, in writexl_alt_app_tex
  ns = utility_xml_namespace(f)
  File "C:\Program\py\pylightxl\pylightxl.py", line 2023, in utility_xml_namespce
    for event, elem in ET.iterparse(file, events):
  File "C:\Program\Python3\lib\xml\etree\ElementTree.py", line 1229, in iterato
    data = source.read(16 * 1024)
UnicodeDecodeError: 'gbk' codec can't decode byte 0xa8 in position 412: illegal
multibyte sequence

**Suggestion for fix**:

def writexl_alt_app_text(db, filepath):

    with open(filepath, 'r', encoding='utf-8') as f:

**Comment by PydPiper** [comment]
Hi @Leslielu thank you for considering using pylightxl for your project. I am taking a look at this issue now

**Comment by PydPiper** [comment]
Thank you for submitting this issue. We had made the update to include `encoding='utf-8'`. Please update pylightxl to v1.56. Please let us know if you run into anything else!

**Comment by roney-nd** [comment]
```
Traceback (most recent call last):
  File ".\xxxx.py", line 66, in cleanup
    xl.writexl(self.xlsxData, 'AAA.xlsx')
  File "C:\Users\xxxx\AppData\Local\Programs\Python\Python37\lib\site-packages\pylightxl\pylightxl.py", line 639, in writexl
    writexl_alt_writer(db, fn)
  File "C:\Users\xxxx\AppData\Local\Programs\Python\Python37\lib\site-packages\pylightxl\pylightxl.py", line 687, in writexl_alt_writer
    path_wb=temp_folder + '/xl/workbook.xml')
  File "C:\Users\xxxx\AppData\Local\Programs\Python\Python37\lib\site-packages\pylightxl\pylightxl.py", line 945, in writexl_alt_getsheetref
    ns = utility_xml_namespace(f)
  File "C:\Users\xxxx\AppData\Local\Programs\Python\Python37\lib\site-packages\pylightxl\pylightxl.py", line 2318, in utility_xml_namespace
    for event, elem in ET.iterparse(file, events):
  File "C:\Users\xxxx\AppData\Local\Programs\Python\Python37\lib\xml\etree\ElementTree.py", line 1224, in iterator
    data = source.read(16 * 1024)
UnicodeDecodeError: 'gbk' codec can't decode byte 0xba in position 910: illegal multibyte sequence
```
@PydPiper There are still many `open` without `utf8` (Version: 1.61)
