### ISSUE TITLE
Error opening Excel file

### ISSUE THREAD

**Issue by sbardian** [PydPiper/pylightxl#55]
**Pylightxl Version**:  1.57
**Python Version**:  3.9.1

**Summary of Bug/Feature**:
Error opening excel file because of Sheet ID issue.  See issue #53 

**Traceback**:
```
Traceback (most recent call last):
  File "D:\FolhaCaixa2\lusitania\api.py", line 46, in <module>
    lusitania.convert()
  File "D:\FolhaCaixa2\utils.py", line 89, in convert
    db = xl.readxl('Lusitania_Recibos.xlsx')
  File "C:\Users\Andre\.virtualenvs\FolhaCaixa2-LlgGVunk\lib\site-packages\pylightxl\pylightxl.py", line 119, in readxl
    wb_rels = readxl_get_workbook(fn)
  File "C:\Users\Andre\.virtualenvs\FolhaCaixa2-LlgGVunk\lib\site-packages\pylightxl\pylightxl.py", line 235, in readxl_get_workbook
    sheetId = int(rId.split('rId')[-1])
ValueError: invalid literal for int() with base 10: 'R47fd958b504b4526'
```

**Suggestion for fix**:
PR:  #56

**Comment by PydPiper** [comment]
@sbardian Thank you for submitting this. Sorry i've been tied up with school i will make time to run through this PR this week! Thanks again

**Comment by PydPiper** [comment]
@sbardian good stuff, thank you for contributing! The PR is merged into the master, i will take a look at few more features before releasing the new version with this fix. Until then please use the master branch
